--return {
--  "williamboman/mason.nvim",
--  dependencies = {
--    "williamboman/mason-lspconfig.nvim",
--    "WhoIsSethDaniel/mason-tool-installer.nvim",
--    "VonHeikemen/lsp-zero.nvim",
--  },
--  config = function()
--    -- import mason
--    local mason = require("mason")
--    local lsp_zero = require("lsp-zero")
--
--    -- import mason-lspconfig
--    local mason_lspconfig = require("mason-lspconfig")
--
--    local mason_tool_installer = require("mason-tool-installer")
--    -- enable mason and configure icons
--    mason.setup({
--      ui = {
--        icons = {
--          package_installed = "✓",
--          package_pending = "➜",
--          package_uninstalled = "✗",
--        },
--      },
--    })
--
--    mason_lspconfig.setup({
--      -- list of servers for mason to install
--      ensure_installed = {
--        "tsserver",
--        "html",
--        "cssls",
--        "tailwindcss",
--        "svelte",
--        "lua_ls",
--        "graphql",
--        "emmet_ls",
--        "prismals",
--        "pyright",
--      },
--      handlers = { lsp_zero.default_setup },
--      -- auto-install configured servers (with lspconfig)
--      automatic_installation = true, -- not the same as ensure_installed
--    })
--
--    mason_tool_installer.setup({
--      ensure_installed = {
--        "prettier", -- prettier formatter
--        "stylua", -- lua formatter
--        "isort", -- python formatter
--        "black", -- python formatter
--        "pylint", -- python linter
--        "eslint_d", -- js linter
--      },
--    })
--  end,
--}
return {}
