-- local puglins =  {
--   {
--     "rust-lang/rust.vim",
--     ft = "rust",
--     init = function()
--       vim.g.rustfmt.autosave = 1
--     end,
--   },
--   {
--     "simrat39/rust-tools.nvim",
--     ft = "rust",
--     dependencies = "neovim/nvim-lspconfig",
--     opts = function()
--       return require "custom.configs.rust-tools"
--     end,
--     config = function(_, opts)
--       require('rust-tools').setup(opts)
--     return
--   },
-- }
--
-- return puglins
--
return {}
